In [ ]:
#!pip install -q pandas numpy scikit-learn xgboost

Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [8]:
train = pd.read_csv("C:/Users/USER/Desktop/프로젝트/PRISM/project2/data/train.csv")
test = pd.read_csv("C:/Users/USER/Desktop/프로젝트/PRISM/project2/data/test.csv")
submission = pd.read_csv("C:/Users/USER/Desktop/프로젝트/PRISM/project2/data/sample_submission.csv")

In [9]:
train_df = train.copy
test_df = test.copy
submi = submission.copy

In [24]:
train

              ID SUBCLASS    A2M AAAS AADAT  ... ZNRF4 ZPBP ZW10  ZWINT ZYX
0     TRAIN_0000    KIPAN     WT   WT    WT  ...    WT   WT   WT     WT  WT
1     TRAIN_0001     SARC     WT   WT    WT  ...    WT   WT   WT     WT  WT
2     TRAIN_0002     SKCM  R895R   WT    WT  ...    WT   WT   WT     WT  WT
3     TRAIN_0003     KIRC     WT   WT    WT  ...    WT   WT   WT     WT  WT
4     TRAIN_0004   GBMLGG     WT   WT    WT  ...    WT   WT   WT     WT  WT
...          ...      ...    ...  ...   ...  ...   ...  ...  ...    ...  ..
6196  TRAIN_6196     LUAD     WT   WT    WT  ...    WT   WT   WT     WT  WT
6197  TRAIN_6197      LGG     WT   WT    WT  ...    WT   WT   WT     WT  WT
6198  TRAIN_6198     COAD     WT   WT    WT  ...    WT   WT   WT  T181S  WT
6199  TRAIN_6199     TGCT     WT   WT    WT  ...    WT   WT   WT     WT  WT
6200  TRAIN_6200     SKCM     WT   WT    WT  ...    WT   WT   WT     WT  WT

[6201 rows x 4386 columns]

In [26]:
train.describe()

                ID SUBCLASS   A2M  AAAS AADAT  ... ZNRF4  ZPBP  ZW10 ZWINT   ZYX
count         6201     6201  6201  6201  6201  ...  6201  6201  6201  6201  6201
unique        6201       26   141    43    25  ...    61    53    53    35    41
top     TRAIN_6200     BRCA    WT    WT    WT  ...    WT    WT    WT    WT    WT
freq             1      786  6053  6157  6176  ...  6139  6143  6142  6166  6159

[4 rows x 4386 columns]

In [27]:
print(train.loc[0])

ID          TRAIN_0000
SUBCLASS         KIPAN
A2M                 WT
AAAS                WT
AADAT               WT
               ...
ZNRF4               WT
ZPBP                WT
ZW10                WT
ZWINT               WT
ZYX                 WT
Name: 0, Length: 4386, dtype: object

In [31]:
print(train["A2M"].loc[1])

WT

In [32]:
print(train.columns)

Index(['ID', 'SUBCLASS', 'A2M', 'AAAS', 'AADAT', 'AARS1', 'ABAT', 'ABCA1',
       'ABCA2', 'ABCA3',
       ...
       'ZNF292', 'ZNF365', 'ZNF639', 'ZNF707', 'ZNFX1', 'ZNRF4', 'ZPBP',
       'ZW10', 'ZWINT', 'ZYX'],
      dtype='object', length=4386)

In [33]:
print(train.columns[0])

ID

In [35]:
for i in range(2, len(train.columns)-1):
    train.rename(columns={train.columns[i]:i-1})

print(train.columns)

Index(['ID', 'SUBCLASS', 'A2M', 'AAAS', 'AADAT', 'AARS1', 'ABAT', 'ABCA1',
       'ABCA2', 'ABCA3',
       ...
       'ZNF292', 'ZNF365', 'ZNF639', 'ZNF707', 'ZNFX1', 'ZNRF4', 'ZPBP',
       'ZW10', 'ZWINT', 'ZYX'],
      dtype='object', length=4386)